# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ecedf78dcb22e20ab4454704cbb72a2718c0ad67213a7823e0eadeab4d97908c30cb266a7c51fd1f7641055e0510697543f10cfece610f71b7c0cef895f0294

test:
  secret_key_base: 147cf12b3c071fb800c531b2b8ec9f1a19e44ba901109f978137779c4e2866c3e9747e0b1b4eb3426b019f7b4835229ff603a2d6916941669c81a84482207211

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
